 version: 2.1
 
 orbs:
   docker-cache: cci-x/docker-registry-image-cache@0.2.12

 commands:
  build_separated_app:
    description: "A command to build a specific app in a specific angular config"
    parameters:
      app_name:
        type: string
        default: null
      angular_config:
        type: string
        default: "production"
    steps:
      - checkout
      - run: echo $Test1
      - run: echo $Test3
      - run:
          name: build app in a Docker
          no_output_timeout: 1h
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username brianoh1979 --password-stdin
            mkdir -p workspace/images
            DOCKER_IMAGE_NAME="front-dist"
            if [ "<< parameters.angular_config >>" == "fast" ] ; then
              DOCKER_IMAGE_NAME="front-fast"
            fi
            if ! docker image pull $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG ; then
              docker build --build-arg ANGULAR_CONFIG=<< parameters.angular_config >> --build-arg APP_NAME=<< parameters.app_name >> --progress plain --target dist-separated-app -t front-<< parameters.app_name >> .
              docker image save front-<< parameters.app_name >> > workspace/images/front-<< parameters.app_name >>.gz
            fi
      - persist_to_workspace: # persist the saved Docker image in the workspace to share it with next job
          root: workspace
          paths:
            - images

 workflows:
   test-and-publish:
     jobs:
#       - test-orb-hub
       - with-dlc

 jobs:
   with-dlc:
      machine:
        image: ubuntu-1604:201903-01
        docker_layer_caching: true
      environment:
        DOCKER_BUILDKIT: "1"
      steps:
        - checkout
        - build_separated_app:
            app_name: "adhesion"
            angular_config: "fast"
        - build_separated_app:
            app_name: "health"
            angular_config: "fast"

